### ISSUE TITLE
I can't get it working

### ISSUE THREAD

**Issue by antton** [Luperi/PageAnnotatorBundle#3]
Hi, 
I fork your project and try to install it following your comments but I can't get it working.
Could you help me a little bit.

After I change composer.json and send composer to install the required dependencies, I'm unable to find the /app/appKernel.php file. I don't know why but I can't find even the src.

Is it the complete code or Am I doing somethins wrong?

Thanks!

**Comment by Luperi** [comment]
Hi,

The file you are searching for is in your symfony project and automatically created. 
It contains all the "installations" of external bundles.

Thank you!
Luca

**Comment by Luperi** [comment]
Any news @antton ?

**Comment by antton** [comment]
It works!

You can close the issue. Thanks
