### ISSUE TITLE
Annotator 2.x

### ISSUE THREAD

**Issue by Kwadz** [Luperi/PageAnnotatorBundle#4]
Hello,

Is there a plan to implement Annotator in his 2.x version?

Thanks

**Comment by Luperi** [comment]
Hi! For the moment no, because I'm too busy due to other business. Are there many differences between the actual version of annotator and the 2.x one? 

Thank you.

**Comment by Kwadz** [comment]
A priori yes, there is some information here: https://github.com/openannotation/annotator/releases
